<?php

/**
 * @file
 * Code for the OFF Idea Feature feature.
 */

include_once 'off_idea_feature.features.inc';

/**
 * Implements hook_flag_flag().
 */
function off_idea_feature_flag_validate($action, $flag, $entity_id, $account, $skip_permission_check, $flagging) {
  if ($flag->name === "idea_vote") {
    if ($action === 'flag') {
      $flags = db_select('flagging', 'f')
        ->fields("f")
        ->condition('uid', $account->uid, "=")
        ->execute();
      $x = $flags->rowCount();
      if ($flags->rowCount() >= 3) {
        return t("You have allready placed three votes, and you will have to remove a vote before you can add more.");
      }
    }
  }
}
